repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: .venv/bin/ruff check
        language: system
        types: [python]
        args: [--fix]
      - id: basedpyright
        name: basedpyright
        entry: .venv/bin/basedpyright
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
