[project]
name = "experiment-monorepo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "trl>=0.26.2",
    "datasets>=2.14.0",
    "modal",
    "wandb>=0.24.0",
    "pillow>=12.1.0",
]
